sudo: required
language: ruby
rvm:
- 2.0.0
- 2.1.4
- 2.2.0
env:
- DB=sqlite
- DB=mysql
- DB=postgresql
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec spec/
before_script:
- mysql -e 'create database travis_ci_test'
- psql -c 'create database travis_ci_test' -U postgres
notifications:
  slack:
    secure: A1tP3vZVdIwGmFDgfwBYjKnx/dJRf6kea4kSpJ0SuYVAaCKOxI12jlqieG8a7JDLUmfFqEBv7+UVTnWPyz+DWfuUN+MewpUr0HAsDaMGI+TMZRDVs3K1MMk2w9SuzIyXeU0tTfHKBxBNQBzywzgtzae4exni7q09HQDphwwYuCV7J67fJBlLZoH0p4sxbma+kM2rt1YRAp3L5RxYHpZcwT/ReSQODH0MtYN5NLAyo5zchxC469nTpGYbcSuDeb/qxua7cLvQllkOa4A9R0FXful7LTXiDvmmgYtr9CdZsoT7e+bggAhJ3uC9Timwp77L9as0gNCG1KwmU65+iFGYTzn9k1/TZUgKQ6ZGgpoQN0mBzMry+ZcbGX67KjxO3QoYo2TTHXDcGJ32MXyg/p5Doz7cjcGz7O2LPJ0VIFcg4oqViL/I2oKUc1lXtrqnsuCS0ad1rgRToGRwad2BbfW5izRzHaXSq/76O+uhJnLv2nTZI06ootJ+mA99DKS7yF/Bdb8/w/XJz5UAho1ZM0TAy0kPHDrzvmzaKYlYfCCDpce+Zf1IkZZ/60xkN8KQ8eLbkn9Jz1oXxrqknvIp4tI31wiC5lD6bbSetiZeEXB7JCCKoWJdprVOXWHRLuxd+bO7GF29wkP/fZBSEQhsoib2/cM77I22h/czvKItKtAwJEM=
deploy:
  provider: heroku
  api_key:
    secure: WP9XpWnXW0cS5+cBaTkxQOGXMonb6+XFFW8w3SIHcdNYXkBkcQbZ6Vq9liGnsXQ7wSUnPo42Ejq2Qmq5e/YKTNLQa/Elz5COrcUMZ37+FhkfoRbdDIN7ZR5qkq4yuV+zmsfHXDX7RS7g9IUuTVJf2KDVBmWBdMyO2+3VeKs3ewhqY+juQ3hhMFwWoNusxdXWp4DznwWeDuf4HmNN0gHc57KpU7X/YtNuVPnK424bSI7WvOaXHhqvIZfTy73iMuKY0OSG+uiP+5nF1Y+7IyrpU1PrznBONoDoPjb1071pTDmJtYrgQppJ51MiEL2s/4C/HEURkD0u4VRpd4t6GT9K3Ukq2W8x2oGIXH7cJmyKxFy93F/gVGKRCowFnroD+J5fyMZjdLwp/R1UBffI2IdCyl+XebBOqPxRKM+fshwoaUMjnt/I1Qa0NOYvhXMfCOK8jWxbdSItUura8A7ASVE3MUS64q6iFCOZLdezgLPv/4iRJOCih+BlCi33vk0cdEJE2cvVeRS/FAoXQiJ+kBO8hDM0dqmL+3bF9wKyOXnakDcWM/ZdtWOAr1GrEjur7yjqRoiWwJYJmib8qlQ2jtqCGxqrAjYCLAsmOQAIgu0taK4tV5LyCf65OzEEH4cdfc6lLNWhKvE9WVjXgLxy4FJFk25wFP856OM5rdsaK1UEN4Q=
  app: project3stevedocsapiv1
  on:
    repo: inocr8/project3_stevedocsAPIv1
    branch: release
