sudo: required
language: ruby
rvm:
- 2.0.0
- 2.1.4
- 2.2.0
env:
- DB=sqlite
- DB=mysql
- DB=postgresql
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec spec/
before_script:
- mysql -e 'create database travis_ci_test'
- psql -c 'create database travis_ci_test' -U postgres
notifications:
  slack:
    secure: A1tP3vZVdIwGmFDgfwBYjKnx/dJRf6kea4kSpJ0SuYVAaCKOxI12jlqieG8a7JDLUmfFqEBv7+UVTnWPyz+DWfuUN+MewpUr0HAsDaMGI+TMZRDVs3K1MMk2w9SuzIyXeU0tTfHKBxBNQBzywzgtzae4exni7q09HQDphwwYuCV7J67fJBlLZoH0p4sxbma+kM2rt1YRAp3L5RxYHpZcwT/ReSQODH0MtYN5NLAyo5zchxC469nTpGYbcSuDeb/qxua7cLvQllkOa4A9R0FXful7LTXiDvmmgYtr9CdZsoT7e+bggAhJ3uC9Timwp77L9as0gNCG1KwmU65+iFGYTzn9k1/TZUgKQ6ZGgpoQN0mBzMry+ZcbGX67KjxO3QoYo2TTHXDcGJ32MXyg/p5Doz7cjcGz7O2LPJ0VIFcg4oqViL/I2oKUc1lXtrqnsuCS0ad1rgRToGRwad2BbfW5izRzHaXSq/76O+uhJnLv2nTZI06ootJ+mA99DKS7yF/Bdb8/w/XJz5UAho1ZM0TAy0kPHDrzvmzaKYlYfCCDpce+Zf1IkZZ/60xkN8KQ8eLbkn9Jz1oXxrqknvIp4tI31wiC5lD6bbSetiZeEXB7JCCKoWJdprVOXWHRLuxd+bO7GF29wkP/fZBSEQhsoib2/cM77I22h/czvKItKtAwJEM=
deploy:
  provider: heroku
  api_key:
    secure: i+zO6kFFYFB+Y7me9Z+/izZ+M/eUJ8927OWu6Np9BTRy5LMTSeMNrMtkYy512qH7LgT+/SQRoQWwKDwZQI/Bf8QYHiTxD0ciUNOAPqApyg7RGxXmgqXn4fIjxkZGf03zUPk1/q1I1i4UysFjEo1/THQBNeQE62vFZya7L8rlfPuVAXOU6fSoNtlrZalZ+uJCwuo0ggBZ4g2n52jl0yQFFg4Zlktp9Jx+LvTVLNF2WLi2Yz4uN9ezuQopYvQ0ecF7u3ld8DkTCMWn4o4lcVNDZjeNlvUmLlHN+lxlZgaQIuh19zhJFiPhGAP5/Pq5lfdS9JslxFEEmMZrvnt2xbl3EDIpmltlHbgOEHyTQVRt3oiPmUk3mcY0x9wiy/nm4FfaIDHVFvHwQ5bj+pZ7ESuYZ+gD+np0prPr8f2DtvZurbWgIt5Mv5DMhFi9jkLZSrB+/gsKjSythnq5L3p0YY06koLMc4gwRnXMhQOjOA3REiBEWxaZkIQDvixMyOiyIeF7NWV7KXKWEj5yEO5T2HGwyMrGgZHeK6YeuQi/nQi129AcnFO8GBY9BKR7cYpRiUhD77KxYZPgTFBWUiENI3EIDrhgIcEjzSPmq0+Yg3JcNtQlUbrFxZeJgINkJNtG/V80d+1IQay5K2VwkbHk0KZ/bp/f2lVcgloc1iNMH6P73QI=
  app: project3stevedocsapiv1
  on:
    repo: inocr8/project3_stevedocsAPIv1
    branch: release
