development: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password:
  host: stevedocsapiv1_db_1

test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres