development: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password:
  host: stevedocsapiv1_db_1

test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres

production:
  url:  <%= ENV["DATABASE_URL"] %>
  adapter: postgresql
  encoding: unicode
  database: stevedocs_api_v1_production
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
  username: stevedocs_api_v1
  password: <%= ENV['STEVEDOCS_API_V1_DATABASE_PASSWORD'] %>

